
import { InpasCitizen, InpasVehicle, InpasWeapon } from '../../types';

export const MOCK_CITIZENS: InpasCitizen[] = [
  {
    id: 'c1',
    firstName: 'Thomas',
    lastName: 'Müller',
    birthDate: '15.05.1985',
    nationality: 'Deutsch',
    residence: 'Berlin',
    gender: 'Männlich',
    address: 'Alexanderplatz 1, 10178 Berlin',
    criminalRecord: ['Diebstahl (2010)', 'Körperverletzung (2015)'],
    openCases: ['Laufendes Verfahren wegen Betrug'],
    licenseStatus: 'Gültig',
    notes: 'Kooperativ bei Kontrollen.'
  },
  {
    id: 'c2',
    firstName: 'Sabine',
    lastName: 'Schmidt',
    birthDate: '22.11.1990',
    nationality: 'Deutsch',
    residence: 'Hamburg',
    gender: 'Weiblich',
    address: 'Reeperbahn 10, 20359 Hamburg',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: 'Keine Auffälligkeiten.'
  },
  {
    id: 'c3',
    firstName: 'Michael',
    lastName: 'Weber',
    birthDate: '03.02.1978',
    nationality: 'Deutsch',
    residence: 'München',
    gender: 'Männlich',
    address: 'Marienplatz 5, 80331 München',
    criminalRecord: ['Trunkenheit im Verkehr (2020)'],
    openCases: [],
    licenseStatus: 'Entzogen',
    notes: 'Aggressiv unter Alkoholeinfluss.'
  },
  {
    id: 'c4',
    firstName: 'Elena',
    lastName: 'Petrova',
    birthDate: '12.08.1992',
    nationality: 'Russisch',
    residence: 'Berlin',
    gender: 'Weiblich',
    address: 'Kurfürstendamm 45, 10719 Berlin',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: 'Spricht fließend Deutsch.'
  },
  {
    id: 'c5',
    firstName: 'Andreas',
    lastName: 'Hoffmann',
    birthDate: '25.06.1982',
    nationality: 'Deutsch',
    residence: 'Köln',
    gender: 'Männlich',
    address: 'Dompropst-Ketzer-Straße 1, 50667 Köln',
    criminalRecord: ['Sachbeschädigung (2018)'],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: 'Bekannter Fußballhooligan.'
  },
  {
    id: 'c6',
    firstName: 'Lisa',
    lastName: 'Wagner',
    birthDate: '09.01.1995',
    nationality: 'Deutsch',
    residence: 'Frankfurt',
    gender: 'Weiblich',
    address: 'Zeil 100, 60313 Frankfurt',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c7',
    firstName: 'Stefan',
    lastName: 'Becker',
    birthDate: '30.04.1975',
    nationality: 'Deutsch',
    residence: 'Stuttgart',
    gender: 'Männlich',
    address: 'Königstraße 20, 70173 Stuttgart',
    criminalRecord: ['Steuerhinterziehung (2012)'],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: 'Geschäftsmann.'
  },
  {
    id: 'c8',
    firstName: 'Maria',
    lastName: 'Schulz',
    birthDate: '18.09.1988',
    nationality: 'Deutsch',
    residence: 'Düsseldorf',
    gender: 'Weiblich',
    address: 'Königsallee 1, 40212 Düsseldorf',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c9',
    firstName: 'Christian',
    lastName: 'Richter',
    birthDate: '05.12.1993',
    nationality: 'Deutsch',
    residence: 'Leipzig',
    gender: 'Männlich',
    address: 'Grimmaische Straße 10, 04109 Leipzig',
    criminalRecord: ['Drogenbesitz (2021)'],
    openCases: ['Verdacht auf Handel mit BTM'],
    licenseStatus: 'Gültig',
    notes: 'Häufige Aufenthalte in bekannten Brennpunkten.'
  },
  {
    id: 'c10',
    firstName: 'Jan',
    lastName: 'Wolf',
    birthDate: '21.07.1980',
    nationality: 'Deutsch',
    residence: 'Dortmund',
    gender: 'Männlich',
    address: 'Westenhellweg 50, 44137 Dortmund',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c11',
    firstName: 'Karin',
    lastName: 'Koch',
    birthDate: '14.03.1968',
    nationality: 'Deutsch',
    residence: 'Essen',
    gender: 'Weiblich',
    address: 'Kettwiger Straße 15, 45127 Essen',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c12',
    firstName: 'Peter',
    lastName: 'Bauer',
    birthDate: '28.10.1972',
    nationality: 'Deutsch',
    residence: 'Bremen',
    gender: 'Männlich',
    address: 'Sögestraße 1, 28195 Bremen',
    criminalRecord: ['Urkundenfälschung (2005)'],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c13',
    firstName: 'Nicole',
    lastName: 'Klein',
    birthDate: '02.05.1998',
    nationality: 'Deutsch',
    residence: 'Dresden',
    gender: 'Weiblich',
    address: 'Prager Straße 5, 01069 Dresden',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c14',
    firstName: 'Frank',
    lastName: 'Schröder',
    birthDate: '11.06.1965',
    nationality: 'Deutsch',
    residence: 'Hannover',
    gender: 'Männlich',
    address: 'Georgstraße 10, 30159 Hannover',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c15',
    firstName: 'Julia',
    lastName: 'Neumann',
    birthDate: '24.12.1991',
    nationality: 'Deutsch',
    residence: 'Nürnberg',
    gender: 'Weiblich',
    address: 'Königstraße 1, 90402 Nürnberg',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c16',
    firstName: 'Markus',
    lastName: 'Schwarz',
    birthDate: '07.03.1987',
    nationality: 'Deutsch',
    residence: 'Duisburg',
    gender: 'Männlich',
    address: 'Königstraße 50, 47051 Duisburg',
    criminalRecord: ['Widerstand gegen Vollstreckungsbeamte (2019)'],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: 'Polizeibekannt.'
  },
  {
    id: 'c17',
    firstName: 'Sandra',
    lastName: 'Zimmermann',
    birthDate: '19.08.1984',
    nationality: 'Deutsch',
    residence: 'Bochum',
    gender: 'Weiblich',
    address: 'Kortumstraße 10, 44787 Bochum',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c18',
    firstName: 'Uwe',
    lastName: 'Krüger',
    birthDate: '13.02.1960',
    nationality: 'Deutsch',
    residence: 'Wuppertal',
    gender: 'Männlich',
    address: 'Alte Freiheit 1, 42103 Wuppertal',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c19',
    firstName: 'Monika',
    lastName: 'Lange',
    birthDate: '01.10.1970',
    nationality: 'Deutsch',
    residence: 'Bielefeld',
    gender: 'Weiblich',
    address: 'Bahnhofstraße 1, 33602 Bielefeld',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  {
    id: 'c20',
    firstName: 'Jürgen',
    lastName: 'Hartmann',
    birthDate: '27.05.1963',
    nationality: 'Deutsch',
    residence: 'Bonn',
    gender: 'Männlich',
    address: 'Münsterplatz 1, 53111 Bonn',
    criminalRecord: [],
    openCases: [],
    licenseStatus: 'Gültig',
    notes: ''
  },
  { id: 'c21', firstName: 'Tim', lastName: 'Schulz', birthDate: '12.04.1995', nationality: 'Deutsch', residence: 'Berlin', gender: 'Männlich', address: 'Torstraße 12, 10119 Berlin', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c22', firstName: 'Sarah', lastName: 'Wagner', birthDate: '28.08.1992', nationality: 'Deutsch', residence: 'Hamburg', gender: 'Weiblich', address: 'Mönckebergstraße 5, 20095 Hamburg', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c23', firstName: 'Lukas', lastName: 'Becker', birthDate: '05.11.1988', nationality: 'Deutsch', residence: 'München', gender: 'Männlich', address: 'Kaufingerstraße 1, 80331 München', criminalRecord: ['Diebstahl (2014)'], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c24', firstName: 'Laura', lastName: 'Hoffmann', birthDate: '19.02.1994', nationality: 'Deutsch', residence: 'Köln', gender: 'Weiblich', address: 'Hohe Straße 10, 50667 Köln', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c25', firstName: 'Julian', lastName: 'Schäfer', birthDate: '03.07.1985', nationality: 'Deutsch', residence: 'Frankfurt', gender: 'Männlich', address: 'Goethestraße 1, 60313 Frankfurt', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c26', firstName: 'Hannah', lastName: 'Koch', birthDate: '14.12.1991', nationality: 'Deutsch', residence: 'Stuttgart', gender: 'Weiblich', address: 'Schloßplatz 1, 70173 Stuttgart', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c27', firstName: 'Maximilian', lastName: 'Bauer', birthDate: '22.05.1982', nationality: 'Deutsch', residence: 'Düsseldorf', gender: 'Männlich', address: 'Schadowstraße 1, 40212 Düsseldorf', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c28', firstName: 'Emma', lastName: 'Richter', birthDate: '09.09.1996', nationality: 'Deutsch', residence: 'Leipzig', gender: 'Weiblich', address: 'Petersstraße 1, 04109 Leipzig', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c29', firstName: 'Felix', lastName: 'Klein', birthDate: '30.01.1989', nationality: 'Deutsch', residence: 'Dortmund', gender: 'Männlich', address: 'Kampstraße 1, 44137 Dortmund', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c30', firstName: 'Mia', lastName: 'Wolf', birthDate: '11.06.1993', nationality: 'Deutsch', residence: 'Essen', gender: 'Weiblich', address: 'Limbecker Straße 1, 45127 Essen', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c31', firstName: 'Moritz', lastName: 'Schröder', birthDate: '25.03.1984', nationality: 'Deutsch', residence: 'Bremen', gender: 'Männlich', address: 'Obernstraße 1, 28195 Bremen', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c32', firstName: 'Lina', lastName: 'Neumann', birthDate: '07.10.1990', nationality: 'Deutsch', residence: 'Dresden', gender: 'Weiblich', address: 'Wilsdruffer Straße 1, 01067 Dresden', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c33', firstName: 'Paul', lastName: 'Schwarz', birthDate: '18.04.1987', nationality: 'Deutsch', residence: 'Hannover', gender: 'Männlich', address: 'Karmarschstraße 1, 30159 Hannover', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c34', firstName: 'Mila', lastName: 'Zimmermann', birthDate: '02.12.1995', nationality: 'Deutsch', residence: 'Nürnberg', gender: 'Weiblich', address: 'Karolinenstraße 1, 90402 Nürnberg', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c35', firstName: 'Jonas', lastName: 'Braun', birthDate: '13.08.1981', nationality: 'Deutsch', residence: 'Duisburg', gender: 'Männlich', address: 'Düsseldorfer Straße 1, 47051 Duisburg', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c36', firstName: 'Lea', lastName: 'Krüger', birthDate: '24.05.1992', nationality: 'Deutsch', residence: 'Bochum', gender: 'Weiblich', address: 'Massenbergstraße 1, 44787 Bochum', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c37', firstName: 'Leon', lastName: 'Hofmann', birthDate: '05.01.1986', nationality: 'Deutsch', residence: 'Wuppertal', gender: 'Männlich', address: 'Poststraße 1, 42103 Wuppertal', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c38', firstName: 'Clara', lastName: 'Weiß', birthDate: '16.09.1994', nationality: 'Deutsch', residence: 'Bielefeld', gender: 'Weiblich', address: 'Niedernstraße 1, 33602 Bielefeld', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c39', firstName: 'Noah', lastName: 'Jung', birthDate: '27.02.1983', nationality: 'Deutsch', residence: 'Bonn', gender: 'Männlich', address: 'Sternstraße 1, 53111 Bonn', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c40', firstName: 'Sofia', lastName: 'Hahn', birthDate: '08.11.1991', nationality: 'Deutsch', residence: 'Münster', gender: 'Weiblich', address: 'Prinzipalmarkt 1, 48143 Münster', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c41', firstName: 'Elias', lastName: 'Vogel', birthDate: '19.06.1988', nationality: 'Deutsch', residence: 'Karlsruhe', gender: 'Männlich', address: 'Kaiserstraße 1, 76131 Karlsruhe', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c42', firstName: 'Frieda', lastName: 'Friedrich', birthDate: '30.03.1996', nationality: 'Deutsch', residence: 'Mannheim', gender: 'Weiblich', address: 'Planken 1, 68161 Mannheim', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c43', firstName: 'Ben', lastName: 'Günther', birthDate: '11.12.1982', nationality: 'Deutsch', residence: 'Augsburg', gender: 'Männlich', address: 'Annastraße 1, 86150 Augsburg', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c44', firstName: 'Ida', lastName: 'Berger', birthDate: '22.08.1993', nationality: 'Deutsch', residence: 'Wiesbaden', gender: 'Weiblich', address: 'Kirchgasse 1, 65185 Wiesbaden', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c45', firstName: 'Luis', lastName: 'Roth', birthDate: '03.05.1985', nationality: 'Deutsch', residence: 'Gelsenkirchen', gender: 'Männlich', address: 'Bahnhofstraße 1, 45879 Gelsenkirchen', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c46', firstName: 'Greta', lastName: 'Beck', birthDate: '14.01.1990', nationality: 'Deutsch', residence: 'Mönchengladbach', gender: 'Weiblich', address: 'Hindenburgstraße 1, 41061 Mönchengladbach', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c47', firstName: 'Finn', lastName: 'Lorenz', birthDate: '25.09.1984', nationality: 'Deutsch', residence: 'Braunschweig', gender: 'Männlich', address: 'Damm 1, 38100 Braunschweig', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c48', firstName: 'Lotte', lastName: 'Baumann', birthDate: '06.06.1995', nationality: 'Deutsch', residence: 'Chemnitz', gender: 'Weiblich', address: 'Straße der Nationen 1, 09111 Chemnitz', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c49', firstName: 'Erik', lastName: 'Frank', birthDate: '17.02.1987', nationality: 'Deutsch', residence: 'Kiel', gender: 'Männlich', address: 'Holstenstraße 1, 24103 Kiel', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c50', firstName: 'Emilia', lastName: 'Albrecht', birthDate: '28.10.1992', nationality: 'Deutsch', residence: 'Aachen', gender: 'Weiblich', address: 'Adalbertstraße 1, 52062 Aachen', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c51', firstName: 'David', lastName: 'Schmid', birthDate: '15.03.1975', nationality: 'Deutsch', residence: 'Berlin', gender: 'Männlich', address: 'Leipziger Str. 45, 10117 Berlin', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c52', firstName: 'Maria', lastName: 'García', birthDate: '22.07.1988', nationality: 'Spanisch', residence: 'Hamburg', gender: 'Weiblich', address: 'Reeperbahn 10, 20359 Hamburg', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c53', firstName: 'Paul', lastName: 'Lefebvre', birthDate: '05.11.1992', nationality: 'Französisch', residence: 'München', gender: 'Männlich', address: 'Maximilianstr. 5, 80539 München', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c54', firstName: 'Elena', lastName: 'Ivanova', birthDate: '19.02.1984', nationality: 'Russisch', residence: 'Köln', gender: 'Weiblich', address: 'Schildergasse 20, 50667 Köln', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c55', firstName: 'Ahmed', lastName: 'Mansour', birthDate: '03.07.1990', nationality: 'Ägyptisch', residence: 'Frankfurt', gender: 'Männlich', address: 'Zeil 15, 60313 Frankfurt', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c56', firstName: 'Yuki', lastName: 'Tanaka', birthDate: '14.12.1995', nationality: 'Japanisch', residence: 'Düsseldorf', gender: 'Weiblich', address: 'Immermannstr. 30, 40210 Düsseldorf', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c57', firstName: 'John', lastName: 'Smith', birthDate: '22.05.1980', nationality: 'Britisch', residence: 'Stuttgart', gender: 'Männlich', address: 'Königstraße 1, 70173 Stuttgart', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c58', firstName: 'Anna', lastName: 'Kowalska', birthDate: '09.09.1986', nationality: 'Polnisch', residence: 'Leipzig', gender: 'Weiblich', address: 'Grimmaische Str. 5, 04109 Leipzig', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c59', firstName: 'Luca', lastName: 'Rossi', birthDate: '30.01.1993', nationality: 'Italienisch', residence: 'Dortmund', gender: 'Männlich', address: 'Westenhellweg 10, 44137 Dortmund', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' },
  { id: 'c60', firstName: 'Sophie', lastName: 'Dubois', birthDate: '11.06.1989', nationality: 'Französisch', residence: 'Essen', gender: 'Weiblich', address: 'Kettwiger Str. 5, 45127 Essen', criminalRecord: [], openCases: [], licenseStatus: 'Gültig', notes: '' }
];

export const MOCK_VEHICLES: InpasVehicle[] = [
  {
    id: 'v1',
    plate: 'TS 1A2',
    ownerId: 'c1',
    ownerName: 'Thomas Müller',
    type: 'PKW',
    brand: 'Volkswagen',
    model: 'Golf 7',
    color: 'Silber',
    firstRegistration: '10.05.2016',
    insuranceStatus: 'Versichert',
    wantedStatus: 'Keine Fahndung'
  },
  {
    id: 'v2',
    plate: 'TS 9B3',
    ownerId: 'c2',
    ownerName: 'Sabine Schmidt',
    type: 'PKW',
    brand: 'BMW',
    model: '320i',
    color: 'Schwarz',
    firstRegistration: '15.11.2018',
    insuranceStatus: 'Versichert',
    wantedStatus: 'Keine Fahndung'
  },
  {
    id: 'v3',
    plate: 'TS 4C8',
    ownerId: 'c3',
    ownerName: 'Michael Weber',
    type: 'PKW',
    brand: 'Mercedes-Benz',
    model: 'C-Klasse',
    color: 'Blau',
    firstRegistration: '20.02.2015',
    insuranceStatus: 'Versichert',
    wantedStatus: 'Keine Fahndung'
  },
  {
    id: 'v4',
    plate: 'TS 2D1',
    ownerId: 'c4',
    ownerName: 'Elena Petrova',
    type: 'PKW',
    brand: 'Audi',
    model: 'A4',
    color: 'Weiß',
    firstRegistration: '05.08.2020',
    insuranceStatus: 'Versichert',
    wantedStatus: 'Keine Fahndung'
  },
  {
    id: 'v5',
    plate: 'TS 8E5',
    ownerId: 'c5',
    ownerName: 'Andreas Hoffmann',
    type: 'PKW',
    brand: 'Ford',
    model: 'Focus',
    color: 'Rot',
    firstRegistration: '12.06.2017',
    insuranceStatus: 'Versichert',
    wantedStatus: 'Fahndung (Diebstahl)'
  },
  {
    id: 'v6',
    plate: 'TS 5F9',
    ownerId: 'c6',
    ownerName: 'Lisa Wagner',
    type: 'PKW',
    brand: 'Opel',
    model: 'Corsa',
    color: 'Grau',
    firstRegistration: '09.01.2019',
    insuranceStatus: 'Versichert',
    wantedStatus: 'Keine Fahndung'
  },
  {
    id: 'v7',
    plate: 'TS 3G2',
    ownerId: 'c7',
    ownerName: 'Stefan Becker',
    type: 'PKW',
    brand: 'Porsche',
    model: '911 Carrera',
    color: 'Gelb',
    firstRegistration: '30.04.2021',
    insuranceStatus: 'Versichert',
    wantedStatus: 'Keine Fahndung'
  },
  {
    id: 'v8',
    plate: 'TS 7H4',
    ownerId: 'c8',
    ownerName: 'Maria Schulz',
    type: 'PKW',
    brand: 'Hyundai',
    model: 'i30',
    color: 'Braun',
    firstRegistration: '18.09.2016',
    insuranceStatus: 'Versichert',
    wantedStatus: 'Keine Fahndung'
  },
  {
    id: 'v9',
    plate: 'TS 1I7',
    ownerId: 'c9',
    ownerName: 'Christian Richter',
    type: 'PKW',
    brand: 'Renault',
    model: 'Clio',
    color: 'Grün',
    firstRegistration: '05.12.2014',
    insuranceStatus: 'Nicht Versichert',
    wantedStatus: 'Keine Fahndung'
  },
  {
    id: 'v10',
    plate: 'TS 6J0',
    ownerId: 'c10',
    ownerName: 'Jan Wolf',
    type: 'PKW',
    brand: 'Skoda',
    model: 'Octavia',
    color: 'Silber',
    firstRegistration: '21.07.2015',
    insuranceStatus: 'Versichert',
    wantedStatus: 'Keine Fahndung'
  },
  { id: 'v11', plate: 'TS 4K2', ownerId: 'c21', ownerName: 'Tim Schulz', type: 'PKW', brand: 'VW', model: 'Golf', color: 'Schwarz', firstRegistration: '12.04.2020', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v12', plate: 'TS 9L3', ownerId: 'c22', ownerName: 'Sarah Wagner', type: 'PKW', brand: 'Audi', model: 'A3', color: 'Silber', firstRegistration: '28.08.2019', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v13', plate: 'TS 2M8', ownerId: 'c23', ownerName: 'Lukas Becker', type: 'PKW', brand: 'BMW', model: '1er', color: 'Blau', firstRegistration: '05.11.2017', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v14', plate: 'TS 7N4', ownerId: 'c24', ownerName: 'Laura Hoffmann', type: 'PKW', brand: 'Ford', model: 'Fiesta', color: 'Rot', firstRegistration: '19.02.2021', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v15', plate: 'TS 3O5', ownerId: 'c25', ownerName: 'Julian Schäfer', type: 'PKW', brand: 'Mercedes', model: 'E-Klasse', color: 'Grau', firstRegistration: '03.07.2018', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v16', plate: 'TS 8P1', ownerId: 'c26', ownerName: 'Hannah Koch', type: 'PKW', brand: 'Opel', model: 'Astra', color: 'Weiß', firstRegistration: '14.12.2020', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v17', plate: 'TS 5Q9', ownerId: 'c27', ownerName: 'Maximilian Bauer', type: 'PKW', brand: 'Toyota', model: 'Corolla', color: 'Silber', firstRegistration: '22.05.2016', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v18', plate: 'TS 1R7', ownerId: 'c28', ownerName: 'Emma Richter', type: 'PKW', brand: 'Hyundai', model: 'i20', color: 'Blau', firstRegistration: '09.09.2021', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v19', plate: 'TS 6S0', ownerId: 'c29', ownerName: 'Felix Klein', type: 'PKW', brand: 'Skoda', model: 'Fabia', color: 'Grün', firstRegistration: '30.01.2015', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v20', plate: 'TS 4T2', ownerId: 'c30', ownerName: 'Mia Wolf', type: 'PKW', brand: 'Renault', model: 'Megane', color: 'Schwarz', firstRegistration: '11.06.2019', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v21', plate: 'TS 9U3', ownerId: 'c31', ownerName: 'Moritz Schröder', type: 'PKW', brand: 'VW', model: 'Passat', color: 'Silber', firstRegistration: '25.03.2014', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v22', plate: 'TS 2V8', ownerId: 'c32', ownerName: 'Lina Neumann', type: 'PKW', brand: 'Audi', model: 'Q3', color: 'Weiß', firstRegistration: '07.10.2018', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v23', plate: 'TS 7W4', ownerId: 'c33', ownerName: 'Paul Schwarz', type: 'PKW', brand: 'BMW', model: '5er', color: 'Schwarz', firstRegistration: '18.04.2017', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v24', plate: 'TS 3X5', ownerId: 'c34', ownerName: 'Mila Zimmermann', type: 'PKW', brand: 'Mercedes', model: 'GLC', color: 'Grau', firstRegistration: '02.12.2021', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v25', plate: 'TS 8Y1', ownerId: 'c35', ownerName: 'Jonas Braun', type: 'PKW', brand: 'Ford', model: 'Mondeo', color: 'Blau', firstRegistration: '13.08.2016', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v26', plate: 'TS 5Z9', ownerId: 'c36', ownerName: 'Lea Krüger', type: 'PKW', brand: 'Toyota', model: 'Yaris', color: 'Rot', firstRegistration: '24.05.2020', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v27', plate: 'TS 1A7', ownerId: 'c37', ownerName: 'Leon Hofmann', type: 'PKW', brand: 'VW', model: 'Tiguan', color: 'Silber', firstRegistration: '05.01.2015', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v28', plate: 'TS 6B0', ownerId: 'c38', ownerName: 'Clara Weiß', type: 'PKW', brand: 'Audi', model: 'A1', color: 'Weiß', firstRegistration: '16.09.2021', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v29', plate: 'TS 4C2', ownerId: 'c39', ownerName: 'Noah Jung', type: 'PKW', brand: 'BMW', model: 'X3', color: 'Schwarz', firstRegistration: '27.02.2014', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v30', plate: 'TS 9D3', ownerId: 'c40', ownerName: 'Sofia Hahn', type: 'PKW', brand: 'Mercedes', model: 'A-Klasse', color: 'Silber', firstRegistration: '08.11.2019', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v31', plate: 'TS 2E8', ownerId: 'c51', ownerName: 'David Schmid', type: 'PKW', brand: 'Mercedes', model: 'S-Klasse', color: 'Silber', firstRegistration: '15.03.2015', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v32', plate: 'TS 7F4', ownerId: 'c52', ownerName: 'Maria García', type: 'PKW', brand: 'Seat', model: 'Ibiza', color: 'Rot', firstRegistration: '22.07.2018', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v33', plate: 'TS 3G5', ownerId: 'c53', ownerName: 'Paul Lefebvre', type: 'PKW', brand: 'Peugeot', model: '308', color: 'Blau', firstRegistration: '05.11.2019', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v34', plate: 'TS 8H1', ownerId: 'c54', ownerName: 'Elena Ivanova', type: 'PKW', brand: 'Lada', model: 'Niva', color: 'Weiß', firstRegistration: '19.02.2014', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v35', plate: 'TS 5I9', ownerId: 'c55', ownerName: 'Ahmed Mansour', type: 'PKW', brand: 'Toyota', model: 'Camry', color: 'Grau', firstRegistration: '03.07.2020', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v36', plate: 'TS 1J7', ownerId: 'c56', ownerName: 'Yuki Tanaka', type: 'PKW', brand: 'Honda', model: 'Civic', color: 'Schwarz', firstRegistration: '14.12.2021', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v37', plate: 'TS 6K0', ownerId: 'c57', ownerName: 'John Smith', type: 'PKW', brand: 'Jaguar', model: 'XF', color: 'Silber', firstRegistration: '22.05.2015', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v38', plate: 'TS 4L2', ownerId: 'c58', ownerName: 'Anna Kowalska', type: 'PKW', brand: 'Skoda', model: 'Superb', color: 'Blau', firstRegistration: '09.09.2017', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v39', plate: 'TS 9M3', ownerId: 'c59', ownerName: 'Luca Rossi', type: 'PKW', brand: 'Fiat', model: 'Tipo', color: 'Rot', firstRegistration: '30.01.2021', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' },
  { id: 'v40', plate: 'TS 2N8', ownerId: 'c60', ownerName: 'Sophie Dubois', type: 'PKW', brand: 'Citroen', model: 'C4', color: 'Weiß', firstRegistration: '11.06.2018', insuranceStatus: 'Versichert', wantedStatus: 'Keine Fahndung' }
];

export const MOCK_WEAPONS: InpasWeapon[] = [
  {
    id: 'w1',
    serialNumber: 'SN12345678',
    type: 'Pistole',
    caliber: '9mm',
    ownerId: 'c1',
    ownerName: 'Thomas Müller',
    registrationDate: '15.05.2010',
    status: 'Legal',
    notes: 'Sportschütze.'
  },
  {
    id: 'w2',
    serialNumber: 'SN87654321',
    type: 'Revolver',
    caliber: '.357 Magnum',
    ownerId: 'c3',
    ownerName: 'Michael Weber',
    registrationDate: '20.02.2015',
    status: 'Sichergestellt',
    notes: 'Gefunden bei Hausdurchsuchung.'
  },
  {
    id: 'w3',
    serialNumber: 'SN11223344',
    type: 'Gewehr',
    caliber: '.223 Remington',
    ownerId: 'c7',
    ownerName: 'Stefan Becker',
    registrationDate: '30.04.2021',
    status: 'Legal',
    notes: 'Jäger.'
  },
  {
    id: 'w4',
    serialNumber: 'SN44332211',
    type: 'Pistole',
    caliber: '.45 ACP',
    ownerId: 'c9',
    ownerName: 'Christian Richter',
    registrationDate: '05.12.2014',
    status: 'Gestohlen',
    notes: 'Als gestohlen gemeldet am 10.01.2022.'
  },
  {
    id: 'w5',
    serialNumber: 'SN55667788',
    type: 'Schrotflinte',
    caliber: '12 Gauge',
    ownerId: 'c12',
    ownerName: 'Peter Bauer',
    registrationDate: '28.10.2012',
    status: 'Legal',
    notes: ''
  },
  { id: 'w6', serialNumber: 'SN-W-1001', type: 'Pistole', caliber: '9mm', ownerId: 'c21', ownerName: 'Tim Schulz', registrationDate: '12.04.2020', status: 'Legal', notes: '' },
  { id: 'w7', serialNumber: 'SN-W-1002', type: 'Pistole', caliber: '9mm', ownerId: 'c23', ownerName: 'Lukas Becker', registrationDate: '05.11.2017', status: 'Legal', notes: '' },
  { id: 'w8', serialNumber: 'SN-W-1003', type: 'Gewehr', caliber: '.308', ownerId: 'c25', ownerName: 'Julian Schäfer', registrationDate: '03.07.2018', status: 'Legal', notes: '' },
  { id: 'w9', serialNumber: 'SN-W-1004', type: 'Pistole', caliber: '9mm', ownerId: 'c27', ownerName: 'Maximilian Bauer', registrationDate: '22.05.2016', status: 'Legal', notes: '' },
  { id: 'w10', serialNumber: 'SN-W-1005', type: 'Pistole', caliber: '9mm', ownerId: 'c29', ownerName: 'Felix Klein', registrationDate: '30.01.2015', status: 'Legal', notes: '' },
  { id: 'w11', serialNumber: 'SN-W-1006', type: 'Gewehr', caliber: '.223', ownerId: 'c31', ownerName: 'Moritz Schröder', registrationDate: '25.03.2014', status: 'Legal', notes: '' },
  { id: 'w12', serialNumber: 'SN-W-1007', type: 'Pistole', caliber: '9mm', ownerId: 'c33', ownerName: 'Paul Schwarz', registrationDate: '18.04.2017', status: 'Legal', notes: '' },
  { id: 'w13', serialNumber: 'SN-W-1008', type: 'Pistole', caliber: '9mm', ownerId: 'c35', ownerName: 'Jonas Braun', registrationDate: '13.08.2016', status: 'Legal', notes: '' },
  { id: 'w14', serialNumber: 'SN-W-1009', type: 'Gewehr', caliber: '.30-06', ownerId: 'c37', ownerName: 'Leon Hofmann', registrationDate: '05.01.2015', status: 'Legal', notes: '' },
  { id: 'w15', serialNumber: 'SN-W-1010', type: 'Pistole', caliber: '9mm', ownerId: 'c39', ownerName: 'Noah Jung', registrationDate: '27.02.2014', status: 'Legal', notes: '' },
  { id: 'w16', serialNumber: 'SN-W-2001', type: 'Pistole', caliber: '9mm', ownerId: 'c51', ownerName: 'David Schmid', registrationDate: '15.03.2015', status: 'Legal', notes: '' },
  { id: 'w17', serialNumber: 'SN-W-2002', type: 'Pistole', caliber: '9mm', ownerId: 'c53', ownerName: 'Paul Lefebvre', registrationDate: '05.11.2019', status: 'Legal', notes: '' },
  { id: 'w18', serialNumber: 'SN-W-2003', type: 'Gewehr', caliber: '.308', ownerId: 'c55', ownerName: 'Ahmed Mansour', registrationDate: '03.07.2020', status: 'Legal', notes: '' },
  { id: 'w19', serialNumber: 'SN-W-2004', type: 'Pistole', caliber: '9mm', ownerId: 'c57', ownerName: 'John Smith', registrationDate: '22.05.2015', status: 'Legal', notes: '' },
  { id: 'w20', serialNumber: 'SN-W-2005', type: 'Pistole', caliber: '9mm', ownerId: 'c59', ownerName: 'Luca Rossi', registrationDate: '30.01.2021', status: 'Legal', notes: '' }
];
